---

- name: restard containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

# - name: restard containerd
#   command: systemctl restart containerd

# - name: restard containerd
#   service:
#     name: containerd
#     state: restarted

# Reload configs
- name: Reload sysctl
  become: true
  command: /sbin/sysctl --system

- name: docker status
  service: 
    name: docker 
    state: started