---
- name: Update apt cache and make sure Vim, Curl and Unzip are installed
  apt:
    name: "{{ item }}"
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true
    loop:
    - curl
    - apt-transport-https
    - vim 
    - git
    - wget
    - kubelet
    - kubectl

- name: Disable swap
  shell : |
    swapoff -a

- name: Install containerd