---

- name: Update OS
  apt:
    update_cache: yes
    force_apt_get: true
    cache_valid_time: 3600
    # upgrade: dist

- name: Add google key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add deb repository for kubenetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install packages
  apt:
    name: "{{item}}"
  loop:
    - git
    - vim 
    - curl
    - wget
    - gnupg2 
    - kubectl
    - kubelet
    - ca-certificates
    - apt-transport-https
    - software-properties-common 

- name: Disable swap
  shell : |
    swapoff -a

- name: Containerd Config
  copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: K8s Config
  copy:
    src: kubernetes.conf
    dest: /etc/sysctl.d/kubernetes.conf
  notify: Reload sysctl

- name: Add Docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add deb repository for docker repo
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker
  when: ansible_distribution_release == "xenial"

- name: Install containerd
  apt:
    update_cache: yes
    force_apt_get: true
    cache_valid_time: 3600
    name: "containerd.io"

- name: Get containerd config 
  command: containerd config default
  register: containerd_config

- name: Write containerd config
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
  notify: restard containerd
