---
# tasks file for master

- name: Check if k8s-master is initialise
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_file

- name: Initializing k8s cluster
  become: true
  become_user: root
  command: kubeadm init --apiserver-advertise-address="192.168.135.10" --pod-network-cidr=192.168.0.0/16 --cri-socket /run/containerd/containerd.sock --upload-certs 
  when: not k8s_admin_file.stat.exists

- name: Check if kubeconfig have been created
  stat:
    path: /home/vagrant/.kube/config
  register: kubeconfig_exist

- name: Creating kubeconfig
  become: true
  become_user: root
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config
  when: not kubeconfig_exist.stat.exists

- name: Install CNI (Calico)
  become: false
  command : kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Getting the join cluster command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy k8s join command in a file locally
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./roles/worker/files/join-command"

- name: Copy kubeconfig locally
  fetch:
    src: /home/vagrant/.kube/config
    dest: ~/.kube/vagrant-cluster.config
    flat: yes

