---
# tasks file for master

- name: Check if k8s-master is initialise
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_file

- name: Initializing k8s cluster
  become: true
  become_user: root
  command: kubeadm init --apiserver-advertise-address="192.168.135.10" --pod-network-cidr=192.168.0.0/16 --cri-socket /run/containerd/containerd.sock --upload-certs 
  when: not k8s_admin_file.stat.exists

- name: Creating kubeconfig
  become: true
  become_user: root
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install CNI (Calico)
  become: false
  command : kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Getting the join cluster command
  command: kubeadm token create --print-join-command
  register: join_command

- debug:
    var: join_command